# Generated by Django 2.2.6 on 2019-11-02 05:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191102_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='id',
        ),
        migrations.AddField(
            model_name='pizza',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.RunSQL(
            'ALTER TABLE public.core_pizza ALTER COLUMN uuid SET DATA TYPE UUID USING (uuid_generate_v4());'
        )
    ]
