# Generated by Django 2.2.6 on 2019-11-02 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191102_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('size', models.CharField(choices=[('L', 'Large'), ('M', 'Medium'), ('S', 'small')], default='S', max_length=1)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='number of pizza-box')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('I', 'In-progress'), ('DE', 'Done'), ('DL', 'Delivered')], default='P', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('pizza_flavour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.Pizza')),
            ],
        ),
    ]
