# Generated by Django 2.2.6 on 2019-11-02 22:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='number of pizza-box', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2147483647)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('I', 'In-progress'), ('DN', 'Done'), ('DL', 'Delivered')], default='P', max_length=2),
        ),
    ]
