# Generated by Django 2.2.6 on 2019-11-03 11:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191102_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='prices',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
